import numpy as np

DEG_TO_RAD=(2.*np.pi)/360.

DEFAULT_WIRE_THICKNESS=7

# base colors
RED    = "#FF0000"
GREEN  = "#00FF00"
BLUE   = "#0000FF"
WHITE  = "#FFFFFF"
BLACK  = "#000000"
ORANGE = "#FFA500"

# phasor animation settings
AXIS_COLOR = WHITE
LINE_COLOR = ORANGE
Z0_LABEL_OFFSET = 0.4
Z0_DOT_COLOR = WHITE
Z_LABEL_OFFSET_INIT = 0.24
Z_LABEL_OFFSET = 0.17
Z_DOT_COLOR = WHITE
SINE_PROP_OFFSET_X = 1.5
SINE_PROP_OFFSET_Y = -1.7

# ACvsDCScene
TESLA_EDISON_SCALE_FACTOR = 1.4
TESLA_EDISON_BUF = 1.1
TESLA_EDISON_TEXT_BUF = 0.1
NAME_LABEL_SCALE_FACTOR = 0.9
TITLE_SCALE_FACTOR = 1.2
TITLE_BUF = 0.2
NOTES_SCALE_FACTOR = 0.6
#NOTES_DISP_DELAY = 3.1 #s
NOTES_DISP_DELAY = 1 #s
TOPSY_BUF = 1.4
TOPSY_SCALE = 1.2
TOPSY_OFFSET = 3.0
TRANS_BUF = 1.4
TRANS_SCALE = 1.3
TRANS_OFFSET = 3.0

# WhatIsACScene
DC_BUFF = 1
DC_SCALE = 0.9
BATTERY_IMAGE_BUF = 0.3
DC_CIRCUIT_BUF_X = 0.4
DC_CIRCUIT_BUF_Y = 0.3
DC_CIRCUIT_SCALE_FACTOR = 1.6
DC_CIRCUIT_LABELED_SCALE_FACTOR = 1.45
AC_CIRCUIT_BUF_X = 0.17
AC_CIRCUIT_BUF_SCL_X = 0.3
AC_CIRCUIT_BUF_Y = 0.85
AC_CIRCUIT_SCALE_FACTOR = 1.3
AC_CIRCUIT_LABELED_SCALE_FACTOR = 1.45
AC_BUF_Y = 3.4

# ACvsDCTimeDomain

# old
# PHASOR_COLOR = BLUE
# SINE_COLOR = BLUE
# CIRCLE_COLOR = RED
# CIRCLE_OPACITY = 0.5625
